
  #██╗   ██╗███████╗██╗   ██╗ ██████╗██╗  ██╗ █████╗ ████████╗
  #████╗  ██║██╔════╝╚██╗ ██╔╝██╔════╝██║  ██║██╔══██╗╚══██╔══╝
  #██╔██╗ ██║█████╗   ╚████╔╝ ██║     ███████║███████║   ██║
  #██║╚██╗██║██╔══╝    ╚██╔╝  ██║     ██╔══██║██╔══██║   ██║
  #██║ ╚████║███████╗   ██║   ╚██████╗██║  ██║██║  ██║   ██║
  #╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

  #Простой чат для вашего сервера

  #Форматы чатов:
global-chat-format: "[g] %player% > {message}"
global-chat-empty: "Глобальный чат не может быть пустым!"

local-chat-format: "[l] %player% > {message}" #{message} - сообщение игрока

localchatradius: 200.0 #Переменная типа double

